--- 

- name: Check the status of the Job
  block: 
    - name: Get CRS API authentication token
      uri:
        validate_certs: no
        url: "https://{{CR_static_IP}}/cr/v5/login"
        method: POST
        headers:
          Content-Type: application/json
          Accept: application/json
        return_content: yes
        body:
            username: "{{username}}"
            password: "{{password}}"
        body_format: json 
      register: results_login
      tags:
        - always
 
    - name: Get the job id status
      uri:
        validate_certs: no
        force_basic_auth: yes
        url: https://{{CR_static_IP}}/cr/v5/policies/{{id1}}/jobs/{{jid1}}    
        method: GET
        headers:
              Content-Type: application/json
              Accept: application/json
              X-CR-AUTH-TOKEN: "{{ results_login.json.accessToken}}"
        body_format: json
        status_code: 200
        return_content: yes
      register: policy_details
      failed_when: policy_details.json.status != "Success"
      tags:
        - get

  rescue:
  - debug:
      msg: "The job is still running and will keep reconnecting until it succeeds."
    tags:
      - get
    
      # Pause for 10 minutes to get the status.
  - pause:
      minutes: "{{pause_time}}"
    tags:
      - add
  - include_tasks: check_job_status.yml
    tags:
      - add