--- 
## Log in to Cr Lab and generate a new token because the old token expires every 50-60 seconds.
- name: Check the status of the Job
  block: 
    - name: Get CRS API authentication token
      uri:
        validate_certs: no
        url: "https://{{CR_static_IP}}/cr/v6/login"
        method: POST
        headers:
          Content-Type: application/json
          Accept: application/json
        return_content: yes
        body:
            username: "{{username}}"
            password: "{{password}}"
        body_format: json 
      register: results_login
      tags:
        - create
## Check the job status by using the job id
    - name: Get the job id status
      uri:
        validate_certs: no
        force_basic_auth: yes
        url: https://{{CR_static_IP}}/cr/v6/policies/{{id1}}/jobs/{{jid1}}    
        method: GET
        headers:
              Content-Type: application/json
              Accept: application/json
              X-CR-AUTH-TOKEN: "{{ results_login.json.accessToken}}"
        body_format: json
        status_code: 200
        return_content: yes
      register: job_id_status
      failed_when: job_id_status.json.status != "Success"
      tags:
        - create

  rescue:
  - debug:
      msg: "The job is still running and will keep reconnecting until it succeeds."
    tags:
      - create
    
# Pause for 10 minutes to get the job status.
  - pause:
      minutes: "{{pause_time}}"
    tags:
      - create
  - include_tasks: check_job_status.yml
    tags:
      - create
