--- 
## validating the copy status, whether locked or unlocked
- name: Get copy details
  uri:
    validate_certs: no
    force_basic_auth: yes
    url: https://{{CR_static_IP}}/cr/v6/policies/{{item.0}}/copies/{{item.1}}
    method: GET
    headers:
        Content-Type: application/json
        Accept: application/json
        X-CR-AUTH-TOKEN: "{{ results_login.json.accessToken}}"
    body_format: json
    status_code: 200
    return_content: yes
  register: copy_lock_after_details
  with_together:
    - "{{id}}"
    - "{{cid}}"
  tags:
    - lock

- debug:
    msg: "{{copy_lock_after_details}}"
## obtaining the copy id when an action has been successfully completed.
- name: Fetching the copy id from the above result
  set_fact:
    copy_id: "{{copy_id}} + ['{{ item.json.id }}']"
  with_items: 
    - "{{ copy_lock_after_details.results}}"
  tags:
    - lock
- debug:
    msg: "{{copy_id}}"
  tags:
    - lock

## Printing the success message with the copy id
- name: printing copy lock action status.
  debug: 
    msg:  Copies have been locked successfully with copy id of {{copy_id}}
  tags:
   - lock




