--- 
## Log in to Cr Lab and generate a new token because the old token expires every 50-60 seconds.

- name: Get CRS API authentication token
  uri:
    validate_certs: "{{crrest_verify_certs}}"
    url: "{{cr_url}}/login"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
    return_content: yes
    body:
        username: "{{crrest_username}}"
        password: "{{crrest_password}}"
    body_format: json 
  register: crrest_login_info
  tags:
    - analysisstatus

- name: Set Login Token
  set_fact:
    crrest_token: "{{crrest_login_info.json.accessToken}}"
    crrest_refresh_token: "{{crrest_login_info.json.refreshToken}}"
  tags:
    - analysisstatus

- name: Get analysis details of the copy
  uri:
    validate_certs: "{{crrest_verify_certs}}"
    force_basic_auth: yes
    url: "{{cr_url}}/policies/{{id1}}/copies/{{cr_restore_copy_source_id1}}"
    method: GET
    headers:
          Content-Type: application/json
          Accept: application/json
          X-CR-AUTH-TOKEN: "{{ crrest_token}}"
    body_format: json
    status_code: 200
    return_content: yes
  register: results_Createpolicy
  tags:
    - analysisstatus

- debug:
    msg: "Copies are good, and we can recover and restore them."
  when:
    - results_Createpolicy.json.lastAnalysisStatus == "Good"
  tags:
    - analysisstatus

- name: Failing the playbook since copy is not good
  fail:
    msg: Failing the playbook since copy is not good and Infected backup set(s) found..
  when: results_Createpolicy.json.lastAnalysisStatus == "Critical"
  tags:
    - analysisstatus



# - name: analysis report
#   uri:
#     validate_certs: no
#     force_basic_auth: yes
#     url: "{{ crrest_base_url }}/copies/{{cr_restore_copy_source_id1}}/analysisreports"
#     method: POST
#     headers:
#           Content-Type: application/json
#           Accept: application/json
#           X-CR-AUTH-TOKEN: "{{ crrest_token}}"
#     body_format: json
#     status_code: 200
#     body:
#       {
#         "List_of_email_addresses": [
#           "cyberrecovery@dell.com"
#         ]
#       }
#   register: results_Createpolicy
#   changed_when: true
#   tags:
#     - mail
