--- 
## Log in to Cr Lab and generate a new token because the old token expires every 50-60 seconds.
- name: Check the status of the Job
  block: 
    - name: Get CRS API authentication token
      uri:
        validate_certs: "{{crrest_verify_certs}}"
        url: "{{cr_url}}/login"
        method: POST
        headers:
          Content-Type: application/json
          Accept: application/json
        return_content: yes
        body:
            username: "{{crrest_username}}"
            password: "{{crrest_password}}"
        body_format: json 
      register: crrest_login_info
      tags:
        - scanstatus

    - name: Set Login Token
      set_fact:
        crrest_token: "{{crrest_login_info.json.accessToken}}"
        crrest_refresh_token: "{{crrest_login_info.json.refreshToken}}"
      tags:
        - scanstatus

## Check the job status by using the job id
    - name: Get the job id status
      uri:
        validate_certs: no
        force_basic_auth: yes
        url: "{{cr_url}}/policies/{{id1}}/jobs/{{jid1}}"    
        method: GET
        headers:
              Content-Type: application/json
              Accept: application/json
              X-CR-AUTH-TOKEN: "{{ crrest_token}}"
        body_format: json
        status_code: 200
        return_content: yes
      register: job_id_status
      failed_when: job_id_status.json.status != "Success"
      tags:
        - scanstatus
  rescue:
  - debug:
      msg: "The job is still running and will keep reconnecting until it succeeds."
    tags:
      - scanstatus
    
# Pause for 10 minutes to get the job status.
  - pause:
      minutes: "{{pause_time}}"
    tags:
      - scanstatus
  - include_tasks: copy_scan_status_check.yml


