---
- name: login to CRS and get the policy deatils
  include_tasks: policy_validation.yml
- name: login to CRS and application details
  include_tasks: app.yml
# #   # tags:
#   #   - check
- name:  Get the point in time copy of the policy
  include_tasks: copy_id.yml
  vars:  
    id1: "{{outer_item}}"
  loop: "{{id}}"
  loop_control: 
    loop_var: outer_item

- name:  Analyze the copy using cyber sense
  include_tasks: copy_scan1.yml
  vars:  
    id1: "{{item.0}}"
    cr_restore_copy_source_id1: "{{item.1}}"
  with_together:
    - "{{id}}"
    - "{{cr_restore_copy_source_id}}" 

- name: checking the analyze status of the copy
  include_tasks: copy_scan_status_check1.yml
  vars:  
    id1: "{{item.0}}"
    jid1: "{{item.1}}"
  with_together:
    - "{{id}}"
    - "{{jid}}" 
#   tags:
#     - check

- name: Get the analysis details of the copy (good/partial)
  include_tasks: analyze_details1.yml
  vars:  
    id1: "{{item.0}}"
    cr_restore_copy_source_id1: "{{item.1}}"
  with_together:
    - "{{id}}"
    - "{{cr_restore_copy_source_id}}" 

- name: recover the copy 
  include_tasks: recovery1.yml
  vars:  
    id1: "{{item.0}}"
    cr_restore_copy_source_id1: "{{item.1}}"
  with_together:
    - "{{id}}"
    - "{{cr_restore_copy_source_id}}" 
