---
- name: login to CRS and get the policy deatils
  include_tasks: policy_validation.yml
  tags:
    - add

- name:  Get the point in time copy of the policy
  include_tasks: copy_id.yml
  vars:  
    id1: "{{outer_item}}"
  loop: "{{id}}"
  loop_control: 
    loop_var: outer_item
  tags:
    - get

- name: recover the copy 
  include_tasks: recovery1.yml
  vars:  
    id1: "{{item.0}}"
    cr_restore_copy_source_id1: "{{item.1}}"
  with_together:
    - "{{id}}"
    - "{{cr_restore_copy_source_id}}" 
  tags:
    - check
    - delete
    - fail
    - recover
