- debug: 
    msg: "{{id1}}"
  tags:
    - recover

- debug: 
    msg: "{{cr_restore_copy_source_id1}}"
  tags:
    - recover
  
# - debug: 
#     msg: "{{sandbox_id1}}"  
#   tags:
#     - recover

- import_tasks: recovery.yml
  tags:
    - recover
